- docs/developer-guide/variables/date.md
Fix typo in documentation for date function
> fix(typo) : date

- docs/architecture/README.md
Fixed some documentation grammatical and  sentence  errors.
> Fixed grammatical errors

- docs/administrator-guide/deployment/docker/README.md
- docs/getting-started/README.md
Copy&pasting the links can be avoided this way.
> Make localhost links active

- docs/administrator-guide/configuration/storage/README.md
Salut, deux typo se sont glisser dans la documentation
> Update type minio and section name instead of azure

- docs/developer-guide/variables/README.md
- docs/developer-guide/variables/basic-usage.md
Bonjour Ludovic,
j'ai retiré les . entre parents et []
> change to variables documentation

- docs/administrator-guide/servers/README.md
* Fixed CLI typos
* Tuned descriptions to match the reality
* Improved syntax & grammar a bit
> Sync Kestra servers

- docs/developer-guide/inputs/README.md
* Added missing HTTP headers.
* Linked to the storage page.
> Describe HTTP headers required for FILE inputs

- blogs/2022-06-28-tips-kafka-streams-distributed.md
Also the topology image is un-readable
> doc: improve the Kafka Streams tip article

- .vuepress/theme/components/Footer.vue
- .vuepress/theme/components/layout/Share.vue
> fix(docs): remove usage of window

- docs/README.md
- docs/contributing/README.md
Added a stub for the Contributing page. We'll add more details to it as we expand other guides and add new assets.
> Add Contributing page

- docs/developer-guide/cicd/README.md
The recently added commands seems to lack documentation.
Feel free to move the added section to a more fitting place.
> Describe CI/CD-related commands

- docs/developer-guide/flow/README.md
Any instance of `taskDefaults` has to feature `values`.
> Fix the Flow sample

- docs/administrator-guide/configuration/others/README.md
- docs/developer-guide/cicd/helpers/README.md
- docs/developer-guide/errors-handling/README.md
- docs/developer-guide/flow/README.md
- docs/developer-guide/outputs/README.md
- docs/developer-guide/tasks/README.md
- docs/developer-guide/variables/README.md
- docs/developer-guide/variables/basic-usage.md
- docs/developer-guide/variables/function/currentEachOutput.md
- docs/getting-started/README.md
- docs/plugin-developer-guide/documentation/README.md
- docs/tutorial/dockers/README.md
- docs/tutorial/errors/README.md
Maybe wait for the release to merge it, but review can already be done
> V0.8 new features

- components/community/Slack.vue
- components/layout/Fixed.vue
- layouts/default.vue
Added both buttons as fixed on all pages
> feat: Slack & Back To Top buttons

- content/docs/03.concepts/index.md
- content/docs/10.plugin-developer-guide/07.outputs.md
> Clarify the difference between Metrics and Outputs 

- content/cookie-policy.md
- content/privacy-policy.md
modification on cookies and Privacy Pages
> Changes on Cookie and Privacy Policy

- content/docs/05.developer-guide/06.storage.md
> fix - 06.storage.md

- content/docs/10.plugin-developer-guide/10.build.md
* Added the link describing the plugin directory.
* Minor styling fixes.
> Link to the plugin dir docs

- components/content/ProseA.vue
> fix(component): fix 404 links when file is not index.md and have title

- content/docs/05.developer-guide/09.templates.md
* Fixed the syntax
* Used a more descriptive names
> Update the Templates example

- content/docs/09.administrator-guide/01.configuration/03.enterprise-edition/authentifications/auths/basic.md
- content/docs/09.administrator-guide/01.configuration/03.enterprise-edition/authentifications/auths/oidc.md
- content/docs/09.administrator-guide/01.configuration/03.enterprise-edition/authentifications/index.md
...also fixed minor auth-related issues.
> Describe creation of the initial user account

- content/docs/05.developer-guide/08.triggers/index.md
> Clarify concurrent Executions from triggers

- content/docs/09.administrator-guide/01.configuration/04.micronaut.md
> fix: Set micronaut link to doc to latest instead of old version

- content/docs/09.administrator-guide/03.monitoring/index.md
* Fixed a Micronaut link
* Clarified Kestra internal endpoints a bit.
> Minor fixes on Monitoring

- content/docs/05.developer-guide/03.scripts.md
- content/docs/09.administrator-guide/02.deployment/01.docker.md
close https://github.com/kestra-io/kestra/issues/1835
> [docs] add Python binary/packages examples

- content/docs/05.developer-guide/02.tasks.md
- content/docs/05.developer-guide/08.triggers/03.webhook.md
- content/docs/09.administrator-guide/04.servers.md
- content/docs/14.troubleshooting.md
> Release 0 11

- content/docs/09.administrator-guide/01.configuration/04.others.md
Related to :
https://github.com/kestra-io/kestra/pull/2081
> feat(): JDBC heartbeat doc

- content/docs/09.administrator-guide/01.configuration/01.databases.md
Fixes [#485](https://github.com/kestra-io/docs/issues/485)
> doc: improve datasource configuration documentation

- assets/styles/docs.scss
Improves the experience for users of a dark theme.
close #451
> Make the blank link icon inherit color

- content/docs/05.developer-guide/03.variables/01.index.md
adding an example based on community questions 
closes https://github.com/kestra-io/kestra/issues/2329
> doc: Add example how to parse pebble in variables

- content/docs/09.administrator-guide/01.configuration/01.databases.md
> fix typos in datasources description

- components/content/ProseImg.vue
close https://github.com/kestra-io/docs/issues/666
My first issue at Kestra is the number of SATAN 😈🔥
> fix(docs): Avoid image size decrease

- content/docs/01.architecture.md
- content/docs/index.md
Corrected the index and architecture docs
> fix(docs): corrected the index and architecture doc

- content/docs/01.architecture.md
- content/docs/03.concepts/01.flows.md
- content/docs/03.concepts/02.executions.md
- content/docs/03.concepts/03.storage.md
- content/docs/05.developer-guide/03.scripts.md
- content/docs/13.contributing/index.md
Corrected the following docs:
**Architecture**
**Concepts**
- Flow
- Execution
- Variables and Storage
**Contributing**
> fix(docs): corrected architecture, concepts and contributing docs

- content/docs/05.developer-guide/01.flow.md
- content/docs/05.developer-guide/02.tasks.md
- content/docs/05.developer-guide/03.scripts.md
- content/docs/05.developer-guide/04.inputs.md
- content/docs/05.developer-guide/08.triggers/index.md
- content/docs/05.developer-guide/concurrency.md
- content/docs/05.developer-guide/namespace-files.md
- content/docs/09.administrator-guide/01.configuration/01.databases.md
- content/docs/09.administrator-guide/01.configuration/03.enterprise-edition/secrets/azure-key-manager/index.md
- content/docs/09.administrator-guide/01.configuration/03.enterprise-edition/secrets/google-secret-manager/index.md
- content/docs/09.administrator-guide/02.deployment/06.ec2.md
- content/docs/16.faq/flows.md
Corrected multiple docs, and major changes are in the 04.inputs.md file.
> fix(docs): corrected multiple docs and inputs doc file

- content/docs/09.administrator-guide/03.monitoring/index.md
fixes https://github.com/kestra-io/kestra/issues/2654
> fix: mention or condition

- components/home/Header.vue
- components/layout/TextScroller.vue
- updates color titles in the text scroller. 
- updates the text scroller event listeners. 
Closes #582  
- On the browser test the home page
> enhance: update color titles

- components/blogs/BlogsList.vue
**Description**
- Fixes minor styling issues related to the blog page
Closes #736 
**How to test**
- Navigate to the mobile view of the blogs
**Screenshot**
**Additional Context**
- ~The scroll on mobile needs to be present as per the `scroll` and `wheel` events to indicate there is more content.~
- ~Once you scroll once it disappears on `mouseout`~
- It hides the overflow scrollbar
> fix: blogs mobile view

- components/blogs/BlogsList.vue
**Description**
- Ensures the community sidebar is right aligned. 
Closes #735 
**How to test**
- Navigate to the `/blogs/` URL
**Screenshot**
> fix: right align community sidebar

- content/docs/04.user-interface-guide/09-namespaces.md
- content/docs/05.developer-guide/03.variables/01.index.md
Namespace variables were not documented.
> Mention Namespace variables

- content/docs/15.migrations/recursive-rendering.md
can be merged only after https://github.com/kestra-io/kestra/pull/2834
> Migration section for recursive rendering

- README.md
Nuxt dev server is configured to 3001/tcp.
> fix(readme): name the correct dev server port

- content/docs/10.administrator-guide/index.md
closes https://github.com/kestra-io/docs/issues/868
coses https://github.com/kestra-io/docs/issues/363
> docs: document minimal requirements

- components/enterprise/Editions.vue
Fixes https://github.com/kestra-io/docs/issues/1023 by using the same class used in the Kestra vs Airflow table
> Fix enterprise table responsiveness on mobile

- content/docs/10.configuration-guide/03.enterprise-edition.md
> Fix invalid enterprise links

- assets/styles/docs.scss
- components/layout/Container.vue
- server/api/plugins.js
Better solution of icon positioning in comparison to #993.
Resolves #966, #981.
> Handled repositioning of the plugin icons

- content/docs/07.concepts/expression/03.filter/string.md
Documented filter added by: https://github.com/kestra-io/kestra/pull/3466
> feat(docs): document 'escapeChar' Pebble filter

- content/blogs/2024-02-29-release-0-15.md
- content/docs/02.installation/02.docker.md
- content/docs/02.installation/03.kubernetes.md
- content/docs/02.installation/04.kubernetes-aws-eks.md
- content/docs/02.installation/05.kubernetes-gcp-gke.md
- content/docs/02.installation/06.kubernetes-azure-aks.md
- content/docs/02.installation/07.restack.md
- content/docs/02.installation/08.aws-ec2.md
- content/docs/02.installation/09.gcp-vm.md
- content/docs/02.installation/10.azure-vm.md
- content/docs/02.installation/11.standalone-server.md
- content/docs/02.installation/12.docker-compose.md
- content/docs/02.installation/13.kestra-cloud.md
- content/docs/02.installation/index.md
- content/docs/04.architecture/scheduler.md
- content/docs/06.workflow-components/06.inputs.md
- content/docs/06.workflow-components/12.retries.md
- content/docs/08.developer-guide/01.storage.md
- content/docs/10.administrator-guide/03.monitoring.md
- content/docs/10.administrator-guide/04.server-cli.md
- content/docs/10.administrator-guide/index.md
Refactored section 2 - installation of the documentation
> refactor(docs): Installation Section

- content/docs/01.getting-started/12.api-reference.md
- content/docs/04.architecture/01.main-components.md
- content/docs/04.architecture/02.server-components.md
- content/docs/04.architecture/03.deployment-architecture.md
- content/docs/04.architecture/04.executor.md
- content/docs/04.architecture/05.worker.md
- content/docs/04.architecture/06.scheduler.md
- content/docs/04.architecture/07.indexer.md
- content/docs/04.architecture/08.webserver.md
- content/docs/04.architecture/09.internal-storage.md
- content/docs/04.architecture/10.multi-tenancy.md
- content/docs/04.architecture/index.md
- content/docs/05.enterprise/03.tenants.md
- content/docs/16.faq/flows.md
Reviewed [Architecture](http://kestra.io/docs/architecture/) to update flow and links
> refactor(docs): improve wording and flow of architecture docs

- content/docs/06.workflow-components/15.descriptions.md
> feat(docs): add flow example for description

- content/docs/10.configuration-guide/micronaut.md
> feat(docs): Add docs for CORS configuration in micronaut

- content/docs/09.administrator-guide/00.requirements.md
Break out software requirements a little so it's clear which components belong to open source and enterprise
> update software requirements

- content/docs/04.workflow-components/05.inputs.md
Closes #1220 
Fixing it now as the corresponding issues are now addressed: https://github.com/kestra-io/kestra/issues/3648 and https://github.com/kestra-io/kestra/issues/3649
> fix(docs): Improve input type documentation

- content/docs/04.workflow-components/05.inputs.md
> feat(docs): Explaining difference between Variables and Inputs

- content/docs/08.developer-guide/07.scripts/bind-mount.md
> fix(docs): Fix the volume-enabled property configuration

- content/docs/05.concepts/expression/02.expression-usage.md
- content/docs/05.concepts/expression/03.filter/index.md
- content/docs/05.concepts/expression/03.filter/object.md
- content/docs/05.concepts/expression/06.tag.md
- content/docs/05.concepts/expression/08.deprecated-handlebars.md
> Update Tag page to use Kestra YAML instead of HTML Tags

- content/docs/08.developer-guide/06.plugins.md
Small update of the plugin guide to clarify versionning.
> doc: custom plugin version

- content/docs/03.tutorial/03.outputs.md
- content/docs/03.tutorial/04.triggers.md
- content/docs/04.workflow-components/09.task-defaults.md
- content/docs/05.concepts/09.task-runners/05.types/04.aws-batch-task-runner.md
- content/docs/05.concepts/09.task-runners/05.types/07.google-cloudrun-task-runner.md
- content/docs/08.developer-guide/01.storage.md
- content/docs/08.developer-guide/07.scripts/output-directory.md
- content/docs/08.developer-guide/07.scripts/working-directory.md
- content/docs/14.best-practices/naming-conventions.md
- public/examples/example-guided-tour.yml
Related: https://github.com/kestra-io/docs/pull/1393
Solves: https://github.com/kestra-io/docs/issues/1346 and https://github.com/kestra-io/kestra/issues/3728
> fix(docs): `outputDir` to `outputFiles` and `localFiles` to `inputFiles`

- content/docs/06.enterprise/04.authentication.md
See [Micronaut Security 4.0 breaking changes](https://micronaut-projects.github.io/micronaut-security/latest/guide/#breaks)
> fix(docs): reflect Micronaut 4 config changes

- content/careers/7.partner-development-manager.md
> feat(docs): add partner development manager job description

- content/docs/15.how-to-guides/google-credentials.md
> feat(docs): Add Google Service Account guide

- components/layout/Header.vue
> Fix Kesra typo in Resources menu

- components/common/SocialsList.vue
> feat(ui): add Youtube to the socials list

- content/docs/05.concepts/expression/03.filter/json.md
> feat(docs): add a detailed example showing JSON manipulations

- content/docs/15.how-to-guides/synchonous-executions-api.md
> feat(docs): how-to guide on synchronous executions API

- content/docs/06.enterprise/faq.md
Updates from Micronaut 4.0
https://micronaut-projects.github.io/micronaut-security/latest/guide/#:~:text=Configuration%20Changes
> update example for timeout

- components/layout/Footer.vue
> Fix footer sentence

- content/docs/09.administrator-guide/03.monitoring.md
Just mention the dedicated Prometheus article.
> feat(docs): link to Prometheus setup article

- content/docs/08.developer-guide/06.plugins.md
Fixes https://github.com/kestra-io/kestra/issues/2449
> doc: plugin developer guide

- components/content/ChildCard.vue
> fixed doc card titles

- content/docs/02.installation/04.kubernetes-aws-eks.md
- content/docs/02.installation/05.kubernetes-gcp-gke.md
- content/docs/02.installation/06.kubernetes-azure-aks.md
There is a mistake in Kubernetes docs for cloud providers.
> Fix disabling postgres in kubernetes

- components/card/Card.vue
- components/enterprise/Header.vue
- components/enterprise/Security.vue
1) I am seeing some unexpected cursor-mouseover and click behaviour on the EE page. Nothing too bad but I'm thinking likely minor with a quickfix.
2) Likewise, I don't think the hero image should be clickable here:
> fixed ee issues

- components/home/Companies.vue
- components/home/Header.vue
- components/layout/Companies.vue
possible also to change the breakpoint here to have animation of logo earlier (approximately when starting to have 4 rows)
> added animation for logos

- content/docs/04.workflow-components/09.plugin-defaults.md
> feat(docs): add documentation on forced: true attribute of pluginDefaults

- content/docs/03.tutorial/01.fundamentals.md
- content/docs/08.developer-guide/01.storage.md
> fix(docs): replace state store with KV store

- content/docs/04.workflow-components/09.plugin-defaults.md
Great page, adding Plugin Defaults now :D
> minor grammar fix

- components/layout/GithubButton.vue
- components/layout/Header.vue
> fixed header

- content/docs/09.administrator-guide/04.server-cli.md
close #1268 
@anna-geller @wrussell1999 wdyt ? I tested it locally and it run perfectly 👍
[credits](https://kestra-io.slack.com/archives/C03FEC452NQ/p1726484989616309?thread_ts=1726232571.943889&cid=C03FEC452NQ) to [@prasanna4742](https://github.com/prasanna4742) for the docker-compose
> Instruction and detailed docker-compose to run services independently

- content/docs/09.administrator-guide/backup-and-restore.md
Metadata backup and restore.
To merge after 0.19.
> feat: metadata backup and restore

- components/use-cases/Card.vue
> fixed issue #1821

- components/content/ProseCode.vue
> fixed code wrap

- content/blogs/2022-10-05-kestra-snowflake.md
- content/blogs/2024-01-08-sentry-plugin.md
- content/blogs/2024-03-21-orchestrate-snowflake-with-kestra.md
- content/docs/04.workflow-components/01.tasks/00.flowable-tasks.md
- content/docs/05.concepts/02.namespace-files.md
- content/docs/14.best-practices/naming-conventions.md
- content/docs/15.how-to-guides/secrets.md
- content/docs/15.how-to-guides/terraform-templating.md
- content/docs/plugin-developer-guide/06.document.md
There is a major change in this file: content/docs/plugin-developer-guide/06.document.md
Do take a look.
> fix(docs): update the document to use fetchType based on updates in v19

- content/docs/09.administrator-guide/16.troubleshooting.md
- package-lock.json
Added examples of skipping executions for flows, namespaces and tenant
> Addeed examples for skipping executions #1648

- content/docs/04.workflow-components/01.tasks/02.scripts/08.logging.md
This addition documents how to emit standard log messages from script tasks.
> feat(docs): describe logging from scripts

- components/use-cases/Card.vue
- components/use-cases/engineers/ExploreBlueprints.vue
https://github.com/user-attachments/assets/17b47252-8412-48d6-90bf-b5d23a965934
Successfully resolved the reloading issue for some use-cases/* pages and also resolved the browser console errors.
> Fix issue #1819 Use Cases pages break when reloaded 

- pages/use-cases/automotive.vue
- pages/use-cases/healthcare.vue
> fixed background healthcare and automotive pages

- components/plugins/PluginsLists.vue
https://kestra.io/plugins?page=1&size=40&category=All+Categories&q=+dbt+
trim space in search
> fixed plugin search

- components/blogs/HighlightBlogCard.vue
> fixed blog images

- .github/CONTRIBUTING.md
Novices might get confused by Nuxt's static "loading" screen.
> feat(docs): mention Nuxt start screen

- content/docs/05.concepts/expression/04.function.md
Closes https://github.com/kestra-io/docs/issues/1843
> feat(docs):  add encrypt, decrypt, fromIon and kv functions to pebble function doc

- content/docs/15.how-to-guides/etl-pipelines.md
> feat(docs): add how-to guide on etl pipelines using duckdb, python and task runners

- content/docs/15.how-to-guides/etl-pipelines.md
> feat(docs): add dbt and spark flows in ETL pipelines how-to guide

- content/docs/15.how-to-guides/terraform-modules-for-triggers.md
- content/docs/15.how-to-guides/terraform-templating.md
- Updated plugin path
- Added link to https://github.com/kestra-io/kestra-flows-template repo
- Give more details to subflow vs terraform module approach
> chore:  refresh terraform how-to guides

- content/docs/15.how-to-guides/debezium.md
Closes #1434 
Reference is taken from the http://debezium.io documentation.
> feat(docs): debezium how to guide

- content/docs/06.enterprise/06.audit-logs.md
- content/docs/09.administrator-guide/purge.md
The number Purge tasks keeps growing - let's bind them together.
> feat(docs): link Purge tasks together

- content/blogs/2024-10-15-deploying-kestra-in-clever-cloud.md
- content/docs/01.getting-started/01.quickstart.md
- content/docs/02.installation/03.docker-compose.md
- content/docs/02.installation/14.podman-compose.md
- content/docs/05.concepts/11.storage.md
- content/docs/09.administrator-guide/03.monitoring.md
- content/docs/09.administrator-guide/index.md
This PR fixes broken links pointing to Configuration Reference for Kestra.
Fixes #1909
> feat(docs): Fix broken links for Configuration Reference for Kestra.

- content/blogs/2023-07-10-release-0-10-blueprints-worker-groups-scripts.md
- content/blogs/2024-10-15-deploying-kestra-in-clever-cloud.md
- content/blogs/release-0-19.md
- content/docs/02.installation/02.docker.md
- content/docs/02.installation/03.docker-compose.md
- content/docs/02.installation/08.aws-ec2.md
- content/docs/02.installation/09.gcp-vm.md
- content/docs/02.installation/10.azure-vm.md
- content/docs/02.installation/11.digitalocean-droplet.md
- content/docs/04.workflow-components/01.tasks/02.scripts/bind-mount.md
- content/docs/05.concepts/system-flows.md
- content/docs/06.enterprise/03.tenants.md
- content/docs/06.enterprise/rbac.md
- content/docs/06.enterprise/scim/authentik.md
- content/docs/06.enterprise/secrets-manager.md
- content/docs/06.enterprise/worker-isolation.md
- content/docs/09.administrator-guide/16.troubleshooting.md
- content/docs/11.migration-guide/0.14.0/recursive-rendering.md
- content/docs/11.migration-guide/0.17.0/volume-mount.md
- content/docs/15.how-to-guides/keycloak.md
- content/docs/15.how-to-guides/ssl-configuration.md
- content/docs/configuration/index.md
- content/docs/plugin-developer-guide/05.unit-tests.md
- content/docs/server-cli/index.md
> feat(docs): standardise configuration to use camelCase

- content/docs/15.how-to-guides/azure-workload-id.md
Adding guide for configuring Kestra to use managed workload ID on Azure to use resources such as the Key Vault
> add guide for managed workload id

- content/blogs/2024-11-06-examples-to-help-build-with-kestra.md
Removed a repeated phrase to improve clarity and readability in the paragraph.
> fix: repeated phrasing in paragraph

- content/docs/configuration/index.md
> Add explanation to big messages protection

- components/home/Header.vue
> Revert "Update Header.vue"

- content/docs/configuration/index.md
Closes https://github.com/kestra-io/kestra-ee/issues/2489.
> fix(): add missing mail service doc

- content/docs/08.ui/02.executions.md
I was looking at this page and noticed some old information. Updated to bring up to date with current version and added some additional details to descriptions of the interface.
> update user interface executions page with added details

- content/docs/06.enterprise/custom-dashboards.md
Making some editorial updates to the text ahead of 0.21 release
> update custom dashboards page

- content/docs/15.how-to-guides/loop.md
Include taskrun.value and taskrun.iteration mention
> update loop how-to guide

- content/docs/01.getting-started/01.quickstart.md
- content/docs/01.getting-started/03.tutorial.md
- content/docs/01.getting-started/07.architecture.md
- content/docs/01.getting-started/10.administrator-guide.md
- content/docs/01.getting-started/12.api-reference.md
- content/docs/01.getting-started/16.contributing.md
- content/docs/01.getting-started/17.how-to-guides.md
- content/docs/01.getting-started/18.community-guidelines.md
Went through our Getting Started section of the documentation to refresh and made some quality, consistency, and clarity edits.
> (chore): quality edits for getting started docs

- content/blogs/2023-08-22-generating-fake-data.md
- content/blogs/2024-01-08-sentry-plugin.md
- content/blogs/2024-01-22-release-0-14.md
- content/blogs/2024-04-04-top-10-cool-features-I-love-about-kestra.md
- content/blogs/2024-11-06-examples-to-help-build-with-kestra.md
- content/blogs/2024-11-25-kestra-vs-jenkins.md
- content/docs/03.tutorial/04.triggers.md
- content/docs/03.tutorial/06.errors.md
- content/docs/04.workflow-components/04.variables.md
- content/docs/04.workflow-components/07.triggers/01.schedule-trigger.md
- content/docs/04.workflow-components/07.triggers/index.md
- content/docs/09.administrator-guide/03.monitoring.md
- content/docs/15.how-to-guides/alerting.md
- content/docs/15.how-to-guides/multiplecondition-listener.md
Updates https://github.com/kestra-io/docs/issues/1990
> Remove Condition from the end of Trigger conditions

- content/docs/06.enterprise/announcements.md
- content/docs/06.enterprise/worker-group.md
Cluster has been changed to Instance and needed to be updated in a couple of places 👍
> (fix): update Cluster to Instance

- components/common/SocialsList.vue
- components/company/Team.vue
- components/icons/TwitterXIcon.vue
- components/layout/Newsletter.vue
Closes #2141 
Need one more commit if approved to use `x.com` & name as `X` or `X (Twitter)`
> X (twitter) 2141

- content/docs/08.ui/01.flows.md
Handle https://github.com/kestra-io/kestra/issues/2065 & https://github.com/kestra-io/kestra/issues/6533
> chore(docs): Update Flow page

- components/overview/Header.vue
Closes #2166 
https://github.com/user-attachments/assets/bb961536-f3bb-49c6-ad5d-8b280b292b40
> fix(ui): line height of heading.

- content/docs/14.best-practices/7.outputs.md
closes https://github.com/kestra-io/docs/issues/2024
> docs: Best practices for handling flow outputs

- content/docs/14.best-practices/8.business-unit-separation.md
closes https://github.com/kestra-io/docs/issues/1996
> docs: Business Units Separation best practices

- content/docs/04.workflow-components/12.retries.md
closes https://github.com/kestra-io/kestra/issues/4418
closes https://github.com/kestra-io/kestra/issues/4412
> fix: maxDuration and timeout docs

- assets/styles/app.scss
- components/plugins/PluginCard.vue
- components/plugins/PluginsLists.vue
better arrow + transparent background
It's not perfect but there is progress.
> fix: layout of tooltips

- components/layout/Header.vue
> fix: on route change always close the menu

- components/content/ChildTableOfContents.vue
- components/content/GuidesChildCard.vue
- components/layout/Announce.vue
- components/layout/Breadcrumb.vue
- composables/useContentHead.ts
- layouts/default.vue
- nuxt.config.ts
- pages/blogs/[...slug].vue
- pages/careers/[...slug].vue
- pages/docs/[...slug].vue
- pages/plugins/[...slug].vue
> fix: add back 3 instances of useContentHead

- content/docs/06.enterprise/02.governance/logshipper.md
Closes https://github.com/kestra-io/docs/issues/2236
> docs(logshipper): add examples for other platforms

- content/docs/09.administrator-guide/ssl-configuration.md
- nuxt.config.ts
https://github.com/kestra-io/docs/issues/2245
> docs(ssl-config): re-add outbound and move to admin guide

- components/common/SocialsList.vue
- components/icons/BlueSkyIcon.vue
- components/layout/Socials.vue
Closes #2282 
Here is the screenshot with BlueSky included:
> feat: add BlueSky to socials list

- content/docs/01.getting-started/03.contributing.md
Connected to https://github.com/kestra-io/kestra/pull/7507
> docs: add kestra devcontainer to contributing guide

- content/docs/06.enterprise/02.governance/tenants.md
Part of https://github.com/kestra-io/kestra-ee/issues/2811
Merge when issue closes.
> docs: add tenant deletion information

- package-lock.json
Resolve Critical CVE-2025-24981 and Low CVE-2024-47764
> fix(sec): resolve Critical CVE-2025-24981 and Low CVE-2024-47764

- content/docs/15.how-to-guides/dynamic-flows.md
> feat(docs): how-to guide on dynamic flows

- content/docs/04.workflow-components/01.flow.md
Updates https://github.com/kestra-io/docs/issues/2070
> feat: add finally as an optional component in the flow

- components/docs/NavToc.vue
> fix(ui): gradient border for toc.

- pages/docs/[...slug].vue
- pages/plugins/[...slug].vue
> fix(ui): padding fix on docs and plugins main content

- content/blogs/release-0-22.md
> Remove TBD

- content/docs/02.installation/03.docker-compose.md
closes https://github.com/kestra-io/docs/issues/2404
> fix(docs): remove admonition mentioning rootless install

- components/enterprise/OrchestraCore.vue
- components/enterprise/ProjectDetails.vue
- components/enterprise/Security.vue
- components/features/EnterpriseEdition.vue
- components/features/Footer.vue
- components/features/scheduling/Header.vue
- components/partners/NticoHeader.vue
- components/price/Slider.vue
- components/use-cases/deployment/Header.vue
- data/retail.js
- pages/features/api-first.vue
- pages/features/code-in-any-language/index.vue
- pages/features/code-in-any-language/julia.vue
- pages/features/code-in-any-language/python.vue
- pages/features/code-in-any-language/r.vue
- pages/overview/index.vue
- pages/use-cases/change-data-capture.vue
- pages/use-cases/ci-cd.vue
- pages/use-cases/databases-managament.vue
- pages/use-cases/disaster-recovery.vue
- pages/use-cases/microservices-orchestration.vue
- pages/use-cases/modern-data-stack.vue
- pages/use-cases/monitoring.vue
- pages/use-cases/provisioning-and-deployment.vue
- pages/use-cases/stories/[id]-[slug].vue
> fix(demo): unify Get a demo CTA

- components/cloud/Features.vue
- components/home/OpenSource.vue
- content/privacy-policy.md
simplification of cloud form + update on privacy + HP numbers
> update privacy + hp + form cloud

- content/docs/16.scripts/00.languages.md
- content/docs/16.scripts/01.commands-vs-scripts.md
- content/docs/16.scripts/03.runners.md
- content/docs/16.scripts/index.md
Fix links in Script Tasks group
> docs(script-tasks): remove extra layers from urls

- assets/styles/docs.scss
Closes https://github.com/kestra-io/docs/issues/2457
> fix(styles): adjust image width.

- components/blogs/BlogDetails.vue
- package-lock.json
> fix: multiple authors on blog

- components/layout/Search.vue
> highlight search keywords in preview and title

- content/docs/08.ui/07.administration/00.triggers.md
closes https://github.com/kestra-io/docs/issues/2497
> docs(triggers): add info about types of triggers shown

- content/docs/01.getting-started/04.docs-contributor-guide.md
- content/docs/05.concepts/08.backfill.md
Closes https://github.com/kestra-io/docs/issues/2500
> docs(backfill): update docs with EE backfill instructions

- assets/styles/app.scss
- pages/plugins/[...slug].vue
Closes https://github.com/kestra-io/docs/issues/2489
> chore(core): fixes the double icon appearing in alert box.

- server/api/mock.ts
Relates to https://github.com/kestra-io/kestra-ee/issues/3520
> feat(api): enhance mock API.

- content/blogs/2024-06-04-release-0-17.md
- content/blogs/release-0-19.md
- content/docs/04.workflow-components/01.tasks/01.runnable-tasks.md
- content/docs/04.workflow-components/15.descriptions.md
- content/docs/11.migration-guide/0.15.0/schedule-conditions.md
- content/docs/15.how-to-guides/pause-resume.md
- content/docs/expressions/index.md
- content/docs/use-cases/03.microservices.md
- content/docs/use-cases/06.python-workflows.md
Closes https://github.com/kestra-io/docs/issues/2529
> docs(api-endpoint): change reqres to our api endpoint

- components/docs/RecursiveNavSidebar.vue
Closes https://github.com/kestra-io/docs/issues/2378
> fix(core): correct active path matching.

- components/plugins/PluginsLists.vue
> fix(core): correct plugin count display

- components/plugins/PluginsLists.vue
- content.config.names.ts
- package-lock.json
> fix(plugins): fix plugin filtering logic

- content/docs/06.enterprise/02.governance/tenants.md
- content/docs/task-runners/03.task-runners-vs-worker-groups.md
- Tenants
- Worker Groups vs Task Runners
> docs(videos): final EE videos

- content/docs/09.administrator-guide/backup-and-restore.md
Closes https://github.com/kestra-io/docs/issues/2544
> docs(backup-restore): add full data backup & restore information

- components/content/Badge.vue
Closes https://github.com/kestra-io/docs/issues/2542
> fix(core): fix the blank badge.

- content/docs/05.concepts/editor.md
Didn't notice this page so added a video to compliment it
> docs(editor): add video

- components/blueprints/Lists.vue
- components/home/Blueprints.vue
- composables/useBlueprintsList.js
- server/api/blueprint.js
Closes https://github.com/kestra-io/docs/issues/2344
> feat(blueprints): random shuffling for blueprints.

- components/price/Heading.vue
- components/price/Table.vue
- pages/pricing/index.vue
Closes https://github.com/kestra-io/docs/issues/2476
> feat(core): enhance table features with tooltips and improved styling.

- content/docs/15.how-to-guides/golang.md
Guide to use new plugin.
Helps: https://github.com/kestra-io/docs/issues/2603
> docs(golang): update guide to use new plugin

- content/docs/task-runners/04.types/01.process-task-runner.md
Solves https://github.com/kestra-io/docs/issues/2602
Need to add the guides on installing with docker.
> docs(process): clarify dependencies

- content/docs/11.migration-guide/0.22.0/renamed-version-property.md
Simply made it easier to understand the requirements.
> chore(docs): link to Internal Storage

- assets/styles/components/header.scss
- components/layout/GithubButton.vue
- components/layout/GithubStargazer.client.vue
> feat(core): brink back old gh star status.

- content/docs/08.ui/00.dashboard.md
* Described querying for labels.
* Improved looks a bit.
> feat(docs): mention labels in dashboards

- content/docs/task-runners/04.types/06.google-batch-task-runner.md
Closes https://github.com/kestra-io/plugin-ee-gcp/issues/65
> docs(gcp-batch): update task runner page with note about network

- components/layout/Header.vue
- utils/menu-items.ts
- utils/menu-sizes.ts
Typescript for comment on menu redesign.
> chore(core): layout header in composition api and ts

- components/home/OpenSource.vue
- components/layout/GithubButton.vue
- components/layout/GithubStargazer.client.vue
Closes https://github.com/kestra-io/docs/issues/2675
> fix(core): remove error display.

- content/blogs/release-0-23.md
- content/docs/11.migration-guide/0.23.0/index.md
Adding notes to migration guide and blog post
> docs(default-tenant): warning note for guides

- content/docs/configuration/index.md
Change environment variable example to lowercase
> fix(docs) lowercase environment variable

- components/docs/RecursiveNavSidebar.vue
- composables/useSidebarScroll.ts
Closes https://github.com/kestra-io/docs/issues/2656
Closes https://github.com/kestra-io/docs/issues/2734
**Now** scroll stay where the sidebar item is.
> fix(core): fixes scroll of content and sidebar scroll to top

- components/docs/RecursiveNavSidebar.vue
Closes https://github.com/kestra-io/docs/issues/2735
> fix(core): fix chevron expand

- content/docs/06.enterprise/03.auth/sso/keycloak.md
Part of https://github.com/kestra-io/kestra-ee/issues/3394
> docs(keycloak): add manage group via claims

- content/docs/06.enterprise/01.overview/02.setup.md
- content/docs/configuration/index.md
Part of https://github.com/kestra-io/kestra-ee/issues/4224
> docs(ee-configuration): add fingerprint dependency

- components/videos/TutorialVideo.vue
- components/videos/TutorialsList.vue
- utils/useYoutube.ts
> feat(core): use youtube thumbnail as source of image instead of strapi

- components/layout/GithubStargazer.client.vue
- composables/useContentHead.ts
Closes https://github.com/kestra-io/docs/issues/2767
> fix: make og:image url absolute

- content/docs/06.enterprise/index.md
> docs(ee-v-cloud): add mention of task runners to comparison

- content/docs/expressions/index.md
Add docs for pebble function timestampMilli
close #2804
> feat(pebble): add docs for pebble function timestampMilli

- content/docs/expressions/index.md
> fix typo of timestampMilli

- content/docs/09.administrator-guide/basic-auth-troubleshooting.md
Part of https://github.com/kestra-io/kestra/issues/10073
> docs(admin-guide): add basicAuth troubleshooting page

- components/content/GuidesChildCard.vue
Closes https://github.com/kestra-io/docs/issues/2842
> fix(core): add more spacing and fix placeholder color

- nuxt.config.ts
- package-lock.json
- server/middleware/maintenance.ts
> fix: move middleware to the server

- components/company/Mission.vue
- components/company/Team.vue
- components/features/OutBox.vue
To fix this issue - https://github.com/kestra-io/docs/issues/2824#issuecomment-3078335862.  -- CC @Nico-Kestra 
and some minor tweaks
> fix(core): fixes image visibility issue on Core layout

- components/plugins/PluginCard.vue
- components/plugins/PluginsLists.vue
- package-lock.json
- package.json
- pages/plugins/[...slug].vue
- pages/plugins/index.vue
- server/api/plugins.ts
closes  #2345
closes kestra-io/plugin-scripts#271
DRAFT: DO NOT MERGE BEFORE 0.24.0 RELEASE
> feat: hide deprecated plugin elements

- content/blogs/2022-02-01-kestra-opensource.md
Markdown emoji doesn't render in the title so replacing with a unicode one.
> blogs(emoji): fix markdown emoji

- content/docs/01.getting-started/selected-plugin-installation.md
Closes https://github.com/kestra-io/docs/issues/2667
> docs(selected-plugins-guide): OSS guide for adding selected plugin install

- content/docs/01.getting-started/01.quickstart.md
Closes https://github.com/kestra-io/docs/issues/2952
> docs(quickstart): add cURL to validate basic auth

- package-lock.json
- package.json
This updates MDC inside the website.
I had some trouble with i18n management compatibility but everything should be peachy now.
Please review.
> chore: update ui-libs with recent mdc

- components/price/Table.vue
- data/compare-features.ts
Closes https://github.com/kestra-io/docs/issues/3053
> fix(core): unify the array for desktop and mobile

- assets/styles/app.scss
- components/common/Pagination.vue
> fix: potential white text on white bg

- content/docs/01.getting-started/selected-plugin-installation.md
Closes https://github.com/kestra-io/docs/issues/3106
> fix(selected-plugins): add trailing slash to command

- content/docs/version-control-cicd/04.git.md
Add information on NamespaceSync and TenantSync to the git page.
> fix(git): add NamespaceSync and TenantSync

- components/price/Table.vue
> Fix (UI): pricing page alignment

- content/docs/configuration/index.md
Linked to the dedicated section to make the storage configuration easier.
> feat(docs): provide Internal storage details

- content/docs/04.workflow-components/01.tasks/index.md
> fix(docs): add links

- components/layout/Header.vue
https://github.com/user-attachments/assets/01159ba5-4ea8-4aef-b783-802ae9ed900a
fixes #3164
> fix: accordion behavior on hover on header

- content/docs/11.migration-guide/0.23.0/default-env-prefix.md
Updated variable references to use lowercase format.
> fix: Updated variable references to use lowercase format.
