- .vuepress/theme/components/home/LandingFeature.vue
There was a typo in Easy to Learn feature on homepage which bothered me. I couldnt find any contribution guideline to fix it properly.
> fix typo in feature

- docs/architecture/README.md
`]` at the end encodes as `%5D`
> Fix broken UI link

- docs/administrator-guide/configuration/enterprise-edition/workers/README.md
- docs/developer-guide/best-practice/README.md
- docs/developer-guide/listeners/README.md
The `org.kestra` namespace is not relevant for the doc anymore. See [#306](https://github.com/kestra-io/kestra/pull/306).
Updated namespaces to the current ones.
> Sync listed namespaces

- docs/plugin-developer-guide/runnable-task/README.md
Validated via the documentation of new plugins.
> doc(plugin): Document that @PluginProperty can be use without attribute

- .vuepress/enhanceApp.js
- docs/README.md
- docs/architecture/README.md
- docs/concepts/flows.md
- docs/developer-guide/errors-handling/README.md
- docs/developer-guide/flow/README.md
- docs/developer-guide/listeners/README.md
- docs/developer-guide/tasks/README.md
- docs/developer-guide/variables/README.md
- docs/developer-guide/variables/basic-usage.md
- docs/developer-guide/variables/deprecated-handlebars/use.md
@tchiotludo I can add a redirect in case we want to keep current SEO rank for the flowable tasks page
> feat(docs): add a global tasks page

- docs/administrator-guide/configuration/databases/README.md
The property has been set to 25ms since https://github.com/kestra-io/kestra/pull/1012/.
> Update the min-poll-interval default value

- components/docs/RecursiveNavSidebar.vue
I don't know if it's the best solution but if we add the index as another nav item it will recursively add all items twice so I ends up hardcoding it
> feat(docs): add overview in doc navigation

- assets/styles/app.scss
This will add a small margin so when there is multiple types there is a small margin between them.
> fix: add a margin to type mark as there can be multiple

- content/docs/07.flow-examples/multiplecondition-listener.md
- public/examples/flows_multiplecondition-listeners.yml
The previous example was wrong and so people were thinking there was a bug with the multiple conditions triggers, here is a functional example with an attempt to explain how it works
link to : https://github.com/kestra-io/kestra/pull/1665
close kestra-io/kestra#1472
> fix(docs): Multipleconditions documentation

- content/docs/02.tutorial/02.inputs.md
I'm using the `kestra/kestra:latest-full` image. Using `default` for under `inputs` doesn't work, but using `defaults` under `inputs` works.
> Edit typo in docs about inputs

- content/docs/09.administrator-guide/01.configuration/01.databases.md
Following same doc structure as for queues configuration, give default values used by HikariCP.
> doc: explicit default values used by HikariCP

- components/docs/RecursiveNavSidebar.vue
Hopefully, this made the icon vs border interaction look a bit cleaner 😌
> Add space between menu item icon and item's border highlight

- content/docs/09.administrator-guide/02.deployment/01.docker.md
* The official release tag `v<release>` was omitted.
* The full/non-full is more distinct now.
* Migrated away from deprecated `plugins/core/tasks/scripts`.
> Make the Docker section more logically structured

- content/docs/05.developer-guide/03.scripts.md
shiki supports `docker` and `dockerfile`
> Fix listing lang

- content/docs/09.administrator-guide/01.configuration/03.enterprise-edition/kafka.md
Kafka topic configuration is a quite important piece of the configuration. This is an attempt add context and examples.
> doc: explain Kafka topic defaults

- content/docs/05.developer-guide/08.triggers/01.schedule.md
- content/docs/05.developer-guide/08.triggers/02.flow.md
- content/docs/05.developer-guide/08.triggers/03.webhook.md
- content/docs/05.developer-guide/08.triggers/index.md
Common properties inherited from `AbstractTrigger` were not documented in the main docs nor the generated docs.
> Document common trigger properties

- content/docs/01.getting-started.md
Should be using `docker-compose`
> Fix typo in 01.getting-started.md

- content/docs/09.administrator-guide/02.deployment/03.manual.md
Hello :wave: 
I've been working with manual deployment, and I encountered an issue which wasn't documented. The problem is that i needed to have `./confs` directory where my kestra is running, else, it would crash because couldn't find the file `confs/application.yml`.
> docs(deployment): add configuration tip for manual deployment

- components/blogs/BlogsList.vue
**Description**
- Snaps into view when the pagination or page items are changed
**Testing**
- Navigate to the `/blogs` page.
- On the bottom of the page, shift the pagination and the page items. 
**What to expect**
- It scrolls to the top view if the pagination changes or the page-items value is less than the previously selected item.
- When the page-items is larger than the previously selected value it retains the last post's viewpoint.
Closes #737
> fix: scroll into view after pagination change

- components/layout/Search.vue
**Description**
- Fixes search view on sm and md devices
**How to test**
- Click on the search and enter an input.
**What to expect**
- The results are correctly padded.
- The category tab overflows as expected.
- Modal is centered
**Screenshot**
Closes #742
> fix: search on mobile devices

- content/docs/05.developer-guide/13.cicd/index.md
The CI/CD-related API behind the scenes is only the webserver.
> fix(doc): specify Kestra server type CI/CD requirement

- content/docs/10.administrator-guide/01.configuration/index.md
Using a modified config based on a full copy of the Kestra `application.yml` may break the app after upgrading.
E.g. changed table/topic names:
https://kestra-io.slack.com/archives/C03FQKXRK3K/p1707221836432279?thread_ts=1707221021.908869&cid=C03FQKXRK3K
> feat(docs): warn about using a full config copy

- content/docs/02.installation/05.kubernetes-gcp-gke.md
Hi,
I noticed a few Azure related words in the [Kubernetes on GCP GKE installation guide](https://kestra.io/docs/installation/kubernetes-gcp-gke).
Here is a quick fix.
> Fix: Replace Azure with GCP vocabulary

- content/docs/02.installation/05.kubernetes-gcp-gke.md
Added instructions for using Kubernetes service accounts for GCS rather than Google service accounts. Also added an example for how to validate that this works.
> fix(docs): validate example for gcs + ksa instructions

- content/docs/18.how-to-guides/index.md
- content/docs/18.how-to-guides/inputs.md
- content/docs/18.how-to-guides/monitoring.md
- content/docs/18.how-to-guides/pause-resume.md
- content/docs/18.how-to-guides/python.md
- content/docs/18.how-to-guides/rollback-and-revision-history.md
- content/docs/18.how-to-guides/secrets.md
- content/docs/18.how-to-guides/slack-webhook.md
- content/docs/18.how-to-guides/webhooks.md
How to titles are now "How to Use..." for consistency
> refactor(docs): Rename how to titles

- content/docs/08.developer-guide/07.scripts/outputs-metrics.md
This pull request is related to issue #1238 
we can see the old URL being used here
https://kestra.io/docs/developer-guide/scripts/outputs-metrics
> Fixed orders.csv uri

- content/docs/15.how-to-guides/python.md
- public/examples/commands_python.yml
Add how to execute flows directly from Python to the Python How-to Guide
> fix(docs): add python execute example

- content/docs/08.developer-guide/06.plugins.md
Updated the plugin build step to use kestra:develop-full instead of kestra:latest-full docker as base docker image tag
> Custom Plugin build step updated in the documentation

- content/docs/03.tutorial/01.fundamentals.md
Hello!
The current link for More Flows Content is taking me to 404 page, this adds the missing `/docs` prefix to the URL.
> Fix more info Flow Link 01.fundamentals.md

- content/docs/02.installation/05.kubernetes-gcp-gke.md
k8s cluster was named incorrectly on line 44. Also modifying name of deployment to `my-kestra` from `my-kestra-cluster` to distinguish from k8s cluster
> fix naming on k8s cluster and kestra deployment

- content/docs/10.configuration-guide/01.database.md
- content/docs/10.configuration-guide/02.storage.md
- content/docs/10.configuration-guide/03.enterprise-edition.md
- content/docs/10.configuration-guide/api-retries.md
- content/docs/10.configuration-guide/elasticsearch.md
- content/docs/10.configuration-guide/enabled.md
- content/docs/10.configuration-guide/encryption.md
- content/docs/10.configuration-guide/endpoints.md
- content/docs/10.configuration-guide/environment.md
- content/docs/10.configuration-guide/jvm.md
- content/docs/10.configuration-guide/kafka.md
- content/docs/10.configuration-guide/logging.md
- content/docs/10.configuration-guide/metrics.md
- content/docs/10.configuration-guide/micronaut.md
- content/docs/10.configuration-guide/plugins.md
- content/docs/10.configuration-guide/server.md
- content/docs/10.configuration-guide/system-flows.md
- content/docs/10.configuration-guide/tasks.md
- content/docs/10.configuration-guide/url.md
- content/docs/10.configuration-guide/usage.md
- content/docs/10.configuration-guide/variables.md
- content/docs/10.configuration-guide/webserver.md
Similar to How-to Guides, remove the repetition from the side menu. Also clean up some of the descriptions so they display better on the cards.
> fix(docs): shorten titles and descriptions for Configuration Section

- content/docs/15.how-to-guides/terraform-modules-for-triggers.md
- Added explanations on how to scale trigger management in case of Terraform codebase.
- Provides an example coming from the repo: https://github.com/kestra-io/kestra-flows-template/blob/b6937f9d95970a4e909687eb64936f5ea3f02c1c/environment/production/dbt/jaffle_shop_classic.tf#L28
> feat(docs): how to modularize triggers with example in kestra-flows-template repo

- content/docs/02.installation/12.standalone-server.md
- nuxt.config.ts
Systemd is the most common way to run services on standalone Linux servers.
Kestra requires a slightly unusual exec command, so this PR provides a basic systemd unit file.
> feat(docs): provide systemd service guidance

- content/docs/02.installation/03.docker-compose.md
Wrong naming standards for the Minio object storage resulted in an Internal server error.
```bash
Internal server error
Internal server error: java.lang.IllegalArgumentException: bucket name ‘minio/warehouse’ does not follow Amazon S3 standards. For more information refer https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html
```
I update it to a compatible naming standard.
From
bucket: minio/warehouse
To
bucket: warehouse
> Updated the Minio naming standards

- content/docs/09.administrator-guide/03.monitoring.md
These metrics were [added](https://github.com/kestra-io/kestra/commit/dc4c78aaf2ebb38390bdf63760fff15ae004ac3a) in v0.18.
> feat(docs): mention worker job metrics

- components/home/Header.vue
something with the new homepage, during the loading, I often see this for few seconds, anything to have a proper layout during the loading ?
> fixed header image

- content/docs/06.enterprise/secrets-manager.md
Community report that current example leads to 💥 
```
Caused by: io.kestra.core.exceptions.KestraRuntimeException: No secret interface can be found for 'kestra.secret.type=azure-secret-manager'. Supported types are: [elasticsearch,jdbc,jdbc,jdbc,google-secret- │
│ manager,vault,aws-secret-manager,azure-key-vault] 
```
> fix(docs): Incorrect type in Azure Key Vault example

- content/docs/05.concepts/04.secret.md
Removed examples that are trying to log secrets. Those are de-facto broken since #3018 .
Also, changed 'password' example to 'myPrivateCode' to avoid user confusion (between variable name and value) since a lot of the content is already about passwords. :)
> fix(doc): Logs do not reveal secrets

- components/company/Platform.vue
- components/features/Footer.vue
- components/features/Header.vue
- components/features/apifirst/Header.vue
- components/features/declaratives/Header.vue
- components/features/language/Header.vue
- components/features/language/sub-pages/Header.vue
- components/home/Header.vue
- components/home/How.vue
- components/layout/Footer.vue
- components/layout/Header.vue
- components/overview/Header.vue
- components/solutions/DetailEmpower.vue
- components/solutions/DetailHeader.vue
- components/use-cases/deployment/EnterpriseEdition.vue
- components/use-cases/deployment/Header.vue
- components/use-cases/engineers/EnterpriseEdition.vue
- components/vs/airflow/Header.vue
- components/vs/dagster/Header.vue
- components/vs/prefect/Header.vue
- data/retail.js
- pages/blueprints/[_slug]/[id]-[slug].vue
- pages/blueprints/index.vue
- pages/faq.vue
- pages/features/api-first.vue
- pages/features/code-in-any-language/index.vue
- pages/features/code-in-any-language/julia.vue
- pages/features/code-in-any-language/python.vue
- pages/features/code-in-any-language/r.vue
- pages/use-cases/databases-managament.vue
Current CTA sends to https://kestra.io/docs/getting-started where the reader needs to continue finding its way to the quickstart instructions.
Let's make it simpler for reader who engage on 'get started' cta, and send them directly to https://kestra.io/docs/getting-started/quickstart#start-kestra
> fix(docs): Getting started CTA should send directly to quickstart guide

- content/docs/15.how-to-guides/conditional-branching.md
pull request addresses issue [#1744](https://github.com/kestra-io/docs/issues/1744) task 1
- https://kestra.io/docs/how-to-guides/conditional-branching
> feat(docs): updated Conditional branching with Switch task

- content/docs/01.getting-started/01.quickstart.md
The Docker command in 'docs/content/docs/01.getting-started/01.quickstart.md' contained invalid line breaks, causing an 'invalid reference format' error. This update removes the unnecessary spaces and ensures proper execution.
> docs: correct Docker run command in Quickstart

- content/blogs/2024-01-08-sentry-plugin.md
- content/docs/03.tutorial/06.errors.md
- content/docs/04.workflow-components/01.tasks/00.flowable-tasks.md
- content/docs/04.workflow-components/11.errors.md
- content/docs/09.administrator-guide/03.monitoring.md
- content/docs/11.migration-guide/0.12.0/listeners.md
- content/docs/15.how-to-guides/conditional-branching.md
> fix(exmaples): Replace examples using `exit 1` with `io.kestra.plugin.core.execution.Fail`

- content/docs/15.how-to-guides/ssl-configuration.md
Fixed missed `kestra` header line in the `KESTRA_CONFIGURATION` section.
> fix(examples) - kestra header line in the KESTRA_CONFIGURATION section

- content/docs/05.concepts/expression/03.filter/numeric.md
- content/docs/05.concepts/expression/03.filter/object.md
- content/docs/05.concepts/expression/03.filter/string.md
Updates #1843 
Add filters:
1. `endsWith` in string filters
2. `toIon` in object filters
3. `flatten` in object filters
Removed `replace` from numeric filters. It is already correctly present under string filters.
> feats(docs): add endsWith and flatten filter to pebble string filter doc

- content/docs/15.how-to-guides/multiplecondition-listener.md
This pull request adds a tutorial for using multiple condition listeners in Kestra workflows. The tutorial demonstrates how to trigger a workflow based on the successful execution of two other flows (`multiplecondition-flow-a` and `multiplecondition-flow-b`) within the last 24 hours.
Changes:
-  Created a new tutorial: Multiple Condition Listener
-  Explained how to set up listeners for two dependent flows.
-  Detailed the activation process, including the conditions for successful execution.
-  Included YAML examples for `multiplecondition_flow_a`, `multiplecondition_flow_b`, and the listener flow.
Why this is needed:
The `MultipleCondition` listener allows users to create more complex workflows where multiple conditions must be met before triggering another flow. This is a helpful …
> Add Documentation for Multiple Condition Listener

- content/docs/09.administrator-guide/purge.md
Tried to point out the queues are handled separately from the Purge tasks.
> feat(docs): clarify queues retention

- content/docs/14.best-practices/managing-pip-dependencies.md
- fails currently with:
```
2024-10-21T18:45:16.860Z DEBUG Using task runner 'io.kestra.plugin.core.runner.Process'
2024-10-21T18:45:16.861Z TRACE Provided 0 input(s).
2024-10-21T18:45:16.873Z TRACE Provided 1 input(s).
2024-10-21T18:45:16.894Z DEBUG Starting command with pid 483 [/bin/sh -c set -e
python -m venv venv
source venv/bin/activate
pip install panda
python /tmp/kestra-wd/tmp/7gJaCiIimNEijTVQ6VqlB7/467293932332219461.py]
2024-10-21T18:45:23.086Z WARN /bin/sh: 3: source: not found
2024-10-21T18:45:23.087Z TRACE io.kestra.core.models.tasks.runners.TaskException: Command failed with code 127
at io.kestra.plugin.core.runner.Process.run(Process.java:155)
at io.kestra.plugin.scripts.exec.scripts.runners.CommandsWrapper.run(CommandsWrapper.java:157)
at …
```
> updating source to be dot activated in python/pandas cache example

- content/docs/02.installation/05.kubernetes-gcp-gke.md
With reference to issue #958 
1) it would be nice if you could annotate the serviceaccount via the helm chart rather than creating a seperate service account for workload identity
2) also, it would be nice if the values.yaml in git had some commented-out examples for configuration: secret: etc
@anna-geller Please have a look
> Annotate ServiceAccount in Helm chart and add commented-out examples in values.yaml

- components/layout/Header.vue
Closes #1919 
Ensured that clicking on the menu takes me to the appropriate page.
> feat: add the Blueprints entry in the menu

- utils/menu-sizes.js
The arrows leading to the menu are misplaced
Fixed arrow:
> adjust placement of menu arrows

- content/docs/09.administrator-guide/high-availability.md
Simply listed the kernel parameter required for handling HA environment, such as AWS OpenSearch cluster upgrades.
Feel free to place the note to a more suitable place.
> feat(docs): mention host HA config parameters

- content/docs/03.tutorial/05.flowable.md
- content/docs/04.workflow-components/04.variables.md
- content/docs/04.workflow-components/06.outputs.md
- content/docs/05.concepts/expression/02.expression-usage.md
- content/docs/11.migration-guide/0.11.0/templates.md
- content/docs/14.best-practices/flows.md
Helps https://github.com/kestra-io/docs/issues/1947
> fix: remove references of EachParallel and EachSequential

- content/docs/09.administrator-guide/backup-and-restore.md
The `restore-queue` sub-command is a part of the EE, hence the `sys-ee` parent command.
> fix(docs): use correct command name

- content/docs/task-runners/03.task-runners-vs-worker-groups.md
The documentation is inaccurate because --server and --api-token are no longer valid arguments. Replace them with the --config argument.
> Update doc for the Task Worker with the new command line

- components/content/Mermaid.vue
- content/docs/04.workflow-components/17.states.md
**Closes https://github.com/kestra-io/docs/issues/1946**
Please review @anna-geller 😃
> docs(ui): Make background color of all mermaid diagrams white or grey so that it displays correctly in dark mode.

- content/docs/01.getting-started/03.tutorial.md
- content/docs/08.ui/01.flows.md
- content/docs/plugin-developer-guide/06.document.md
Related to #103
Document the usage of the JSON Schema to validate a flow.
* Add a section in `content/docs/01.getting-started/03.tutorial.md` to document the usage of the JSON Schema to validate a flow, including instructions for using the JSON Schema in VSCode and mentioning the globally available location for the JSON Schema.
* Add a subsection in `content/docs/08.ui/01.flows.md` to explain JSON Schema usage for flow validation, provide an example of how to use the JSON Schema in the flow editor, and mention the globally available location for the JSON Schema.
* Add a section in `content/docs/plugin-developer-guide/06.document.md` to include JSON Schema usage for flow validation, explain how to generate and use the JSON Schema for plugins, and mention the globally available location for …
> Document the usage of the JSON Schema to validate flow

- components/content/GuidesChildCard.vue
Fixes #2016
Change the class in `components/content/GuidesChildCard.vue` to display 3 guides in a single row instead of 2.
* Modify the class from `col-12 col-md-6` to `col-12 col-md-4` for each guide in the `NuxtLink` component.
> Rework the How-To Guide to allow 3 guides in a single row

- content/docs/04.workflow-components/11.errors.md
Update the global error handler example to output the taskId that failed rather than the handler task. From [Slack](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1736412847684019).
> Update global error handler code example

- content/docs/09.administrator-guide/upgrades.md
Adding grace period details to the "Minimising downtime" section of the upgrades guide per [Slack thread](https://kestra-io.slack.com/archives/C03FQKXRK3K/p1736350483005779).
> Update upgrades to include default grace period setting

- content/docs/11.migration-guide/0.17.0/renamed-plugins.md
The `io.kestra.core.tasks.flows.Flow` was aliased to `io.kestra.plugin.core.flow.Subflow`.
> fix(docs): amend v0.17 renamed plugins

- content/docs/11.migration-guide/0.17.0/json-objects-serialization.md
The JSON Object serialization change got a strong impact on pre-v0.17 expression logic. Added a migration guide:
* mentioning the necessity to adapt the affected expressions
* listting a few examples
> feat(docs): add v0.17 JSON-related migration guide

- pages/plugins/[...slug].vue
- utils/identify.js
remove a suspense tag that made the plugins page load again and again
> fix: massive blink on plugins

- components/features/Header.vue
> fix(ui): line height of Heading under Open source page.

- pages/use-cases/stories/index.vue
Closes https://github.com/kestra-io/docs/issues/2379
Problem:
Matched with the button title and links from the home page:
> fix: correct duplicate get started buttons

- components/community/Guidelines.vue
- content/docs/01.getting-started/04.community-guidelines.md
This PR fixes minor grammar and punctuation issues in the community guidelines:
Changed "**Deployment choice**" to "**Deployment choices**" for correctness.
Added a missing space and comma in "**(Kubernetes, etc.)**".
Fixed spacing in "**flows (YAML)**".
> fix(docs): correct typo in the community guidelines

- content/docs/configuration/index.md
The `plugins` section was not really clear, mainly regarding the plugin defaults.
This PR attempts to:
* sort related sections
* improve section hierarchy
* distinguish between `defaults` and `configurations` (based on https://github.com/kestra-io/kestra/issues/2952)
* add links
> fix(docs): improve `kestra.plugins` clarity

- content/docs/15.how-to-guides/local-flow-sync.md
Change from note to info. Also make the paths clearer by using different names.
Currently unreadable:
> doc(local-flow): fix info block

- components/docs/RecursiveNavSidebar.vue
closes: #2447 
Before:
https://github.com/user-attachments/assets/2bb00708-4b94-4e27-81e8-c0475c6d4bd5
After:
https://github.com/user-attachments/assets/92264be7-75e2-4c31-bc77-8d2eaeca27d1
> scroll active nav item in the viewpoint in left nav

- components/blogs/BlogDetails.vue
> fix: blog authors css

- content/docs/06.enterprise/04.scalability/worker-group.md
- content/docs/07.architecture/02.server-components.md
- content/docs/14.best-practices/8.business-unit-separation.md
- content/docs/oss-vs-paid.md
- content/docs/task-runners/03.task-runners-vs-worker-groups.md
Worker Groups are currently only an EE feature. This PR denotes in strategic doc places that they are unavailable on the Cloud.
> docs(worker-groups): add notes on relevant pages for worker groups

- components/layout/Header.vue
Hi @Piyush-r-bhaskar :wave: 
I made another PR based on a branch here and now it's fixed!
Can you check also on your side please :pray: ?
> fix(ui): avoid header-menu to be displayed when mouse leaves

- components/home/EnterpriseStories.vue
Closes https://github.com/kestra-io/docs/issues/2453
> feat(carousel): automatic carousel animation with a timer.

- content/docs/04.workflow-components/07.triggers/index.md
Check that this is correct, but noticed we don't talk about the changes made [here](https://github.com/kestra-io/docs/issues/2497) in the triggers page.
We had a user who was trying to fetch triggers from the API and didn't get their webhook one which I assume is related to this. Also doesn't display in UI.
> docs(triggers): note about webhook triggers not displaying in the UI or API

- content/docs/plugin-developer-guide/02.task.md
Property validation must be performed at its inner type.
> feat(docs): add validation example

- content/docs/plugin-developer-guide/02.task.md
Add `@Builder.Default` to the defaulted property since the guide explicitly mentions `@SuperBuilder`. Also nuke whitespace prefixes.
> feat(docs): improve property default example

- content/docs/configuration/index.md
As the [0.20.0 migration guide](https://kestra.io/docs/migration-guide/0.20.0/server-configuration#email-server-configuration-has-moved-to-a-different-location) mentions the `kestra.mail-service` has become `kestra.ee.mail-service`. The old config simply doesn't work...
> fix(docs): update mail server config to 0.20+

- content/docs/plugin-developer-guide/02.task.md
Let's make `version` property-related compilation failures clear.
> feat(docs): mention reserverd plugin property name

- content/docs/04.workflow-components/10.subflows.md
This must've been missed in a previous release. Part of https://github.com/kestra-io/kestra-ee/issues/3632
> docs(subflow): add scheduleDate

- content/docs/06.enterprise/03.auth/rbac.md
- content/docs/11.migration-guide/0.22.0/failed-attempts-lockout.md
AFAIK the `security` block should be a child of `kestra`.
> fix(docs): amend property path

- content/docs/05.concepts/11.storage.md
- content/docs/16.scripts/00.languages.md
- content/docs/task-runners/01.overview.md
Here is the new PR @aj-emerich with your suggestions!
To be merged for 0.23 (cc @loicmathieu can you add back the tag please?)
resolves https://github.com/kestra-io/kestra/issues/7373
> [0.23 release] doc(go): add plugin-script-go doc

- content/blogs/release-0-19.md
The blog did not mention the value being Base64-encoded at all (unlike the Configuration page).
Using a non-Base64-compatible value leads to a rather strange error... Let's prevent that.
> fix(docs): make it clear you need Base64 value of secret

- content/docs/15.how-to-guides/golang.md
- content/docs/15.how-to-guides/python.md
- content/docs/16.scripts/00.languages.md
Few tweaks to the language guides:
- Add expression examples
- Fix Go example in the languages supported as it now has an official plugin
> docs(guides): add expressions

- content/docs/configuration/index.md
As https://github.com/kestra-io/kestra/issues/8314 mentions, the trailing `/` is not required anymore.
> fix(docs): do not force trailing slash

- content/docs/04.workflow-components/10.subflows.md
Field `wait` of Subflow is default true, according to https://kestra.io/plugins/core/flow/io.kestra.plugin.core.flow.subflow#properties_wait-body
> fix(docs) default true for wait in Subflow

- content/docs/04.workflow-components/13.timeout.md
As long as https://github.com/kestra-io/kestra/issues/6739 is open, it might be good to mention the limitation that timeout doesn't work for flowable tasks.
> Update 13.timeout.md with runnable task limitation

- content/docs/configuration/index.md
Made the GCP sippet match the ECS' format.
> fix(docs): match ECS format

- components/home/Header.vue
- Adds a floating circular close (X) button to the “Kestra in 60 Seconds” video modal
- Improves UX by allowing users to easily close the modal
Closes #2783
Closes https://github.com/kestra-io/docs/issues/2786
https://github.com/user-attachments/assets/78950500-bcd4-471e-884e-d16610433273
- Run locally with `npm run dev`
- Open homepage
- Click “Kestra in 60 Seconds”
- Verify close button appears top-right
- Click the button and ensure modal closes
> feat: add FAB close (X) button to video modal (#2783)

- components/content/ChildCard.vue
Closes #2872 
This PR fixes the sorting order of version numbers in the Migration Guide component https://github.com/kestra-io/docs/issues/2872 .
Previously, versions were displayed in ascending order, which made it harder to see the latest changes first.
Now, the versions are sorted in descending order so that the most recent version appears at the top.
Before vs After:
> Fix: Sort version numbers in descending order in Migration Guide

- content/docs/expressions/index.md
Doc change in line with https://github.com/kestra-io/kestra/pull/11546
Closes #3125
> fix(pebble): correct return value of timestampMicro in docs

- content/docs/03.tutorial/04.triggers.md
Add a note on the default UTC scheduling and timezone property
> docs(triggers): add note on default UTC scheduling and timezone property
